name: devops-pipeline-new
on: workflow_dispatch
jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Installing Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Virtual env
        run: 
          python3 -m venv venv
          source venv/bin/activate

      - name: Install Flask
        run: pip3 install -r requirement.txt

      - name: Run Application
        run: python app.py
         
